name: Prettier

on:
  pull_request:
    branches: [main, develop]

jobs:
  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn global add prettier

      - name: Check code formatting
        run: |
          yarn prettier:check
          yarn --cwd ./packages/tools/ prettier:check
